name: CI

on:
  push:
    branches: [ master, feature/* ]
  pull_request:
    branches: [ master ]

# Auto-cancel old runs when new commits are pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests (Python 3.9)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r tests/requirements-test.txt

    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --tb=short

    - name: Run integration tests
      run: |
        pytest tests/integration/ -v --tb=short

    - name: Run security tests
      run: |
        pytest tests/security/ -v --tb=short

    - name: Run all tests with coverage
      run: |
        pytest tests/ --cov=bin/parallelr.py --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

