name: Simple Test

on:
  push:
    branches: [ feature/** ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  simple-test:
    name: Simple Test (Python 3.6.8)
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.6.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.6.8'

    - name: Check Python version
      run: |
        python --version
        pip --version

    - name: Install test dependencies
      run: |
        python -m pip install pip==21.3.1 setuptools==58.0.4 wheel==0.36.2
        pip install pytest pytest-cov

    - name: Run simple test
      run: |
        python -c "print('Hello from Python 3.6.8')"
        echo "Simple test passed!"
