name: Simple Test

on:
  push:
    branches: [ feature/* ]
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  simple-test:
    name: Simple Test (Python 3.9)
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Check Python version
      run: |
        python --version
        python -m pip --version

    - name: Install test dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov

    - name: Run simple test
      run: |
        python -c "print('Hello from Python 3.9')"
        echo "Simple test passed!"
