name: Test Suite

on:
  push:
    branches: [ master, feature/** ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Run Tests (Python 3.6.8)
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.6.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.6.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements-test-py36.txt

    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --tb=short

    - name: Run integration tests
      run: |
        pytest tests/integration/ -v --tb=short

    - name: Run security tests
      run: |
        pytest tests/security/ -v --tb=short

    - name: Run all tests with coverage
      run: |
        pytest tests/ --cov=bin/parallelr.py --cov-report=xml --cov-report=term-missing

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    name: Lint Code (Python 3.6.8)
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.6.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.6.8'

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install 'pylint>=2.13.0,<2.14.0' 'flake8>=5.0.0,<6.0.0'

    - name: Run pylint
      run: |
        pylint bin/parallelr.py --disable=C0103,C0114,C0115,C0116 || true

    - name: Run flake8
      run: |
        flake8 bin/parallelr.py --max-line-length=120 --ignore=E501,W503 || true

  test-legacy:
    name: Run Legacy Bash Tests (Python 3.6.8)
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.6.8
      uses: actions/setup-python@v5
      with:
        python-version: '3.6.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests/requirements-test-py36.txt

    - name: Run multi-argument tests
      run: |
        cd test_cases/arguments_mode
        bash test_multi_args_suite.sh

    - name: Run backward compatibility tests
      run: |
        cd test_cases/arguments_mode
        bash run_tests.sh

  summary:
    name: Test Summary
    runs-on: ubuntu-20.04
    needs: [test, lint, test-legacy]
    if: always()

    steps:
    - name: Check test results
      run: |
        echo "Test job status: ${{ needs.test.result }}"
        echo "Lint job status: ${{ needs.lint.result }}"
        echo "Legacy test job status: ${{ needs.test-legacy.result }}"

        if [ "${{ needs.test.result }}" != "success" ]; then
          echo "❌ Tests failed"
          exit 1
        fi

        if [ "${{ needs.test-legacy.result }}" != "success" ]; then
          echo "❌ Legacy tests failed"
          exit 1
        fi

        echo "✅ All tests passed!"
